export default [
  "A luxury of today becomes a necessity of tomorrow",
  "Renunciation will make you an emperor of the three worlds",
  "The longing to attain an ideal dies if no effort is made.",
  "Death is only a change for a better state. Therefore, fear not death.",
  "Every mistake brings its own lesson. Mistake is your best teacher.",
  "All troubles and sufferings contain the hidden seeds of God.",
  "Self-effort is necessary for the attainment of God-realisation.",
  "Spiritual effort must be continuously renewed and patiently persisted in.",
  "Like walking on the razor’s edge, the spiritual path is difficult.",
  "Loka Samastha Sukhino Bhavantu",
  "As you proceed onwards along the spiritual path, joy, peace and bliss deepen and deepen.",
  "Success often comes to those who dare and act. It seldom comes to the timid.",
  "Unless you are inspired by spiritual ideals, it is difficult to keep the sexual instinct in check.",
  "Self-realisation is not for the cowards and weaklings, but for the brave, courageous and strong.",
  "If you are good, the whole world will be good for you.",
  "God gives everything, but He is a very great miser in giving Bhakti or devotion to His devotees.",
  "Live not to satisfy your palate and the senses. But live to realise the self within.",
  "Moderation in everything is the key-note for success in Yoga.",
  "Association with saints and sages is difficult to get. They are inaccessible. Such association is unfailing in its results.",
  "Dwell in the divine. Live and move in it. Get absorbed in the Divine Flame.",
  "Laziness is the father of disappointment and failure.",
  "The essential condition of spirituality is the annihilation of the lower self and rooting out the desire for sensual pleasure.",
  "Desire causes misery and anxiety. Abandon all desires. Be serene and happy.",
  "Dispassion is the enemy of the senses and the friend of Pratyahara.",
  "Practice withdrawal of the senses one by one.",
  "Peace, immortality and eternal bliss can be obtained in God alone.",
  "If you control the Prana, you can control the mind easily.",
  "Remain in the world without getting tainted by it just like the lotus-leaf in the water.",
  "No vision of truth or no vision of God is possible without annihilating the ego.",
  "As food is necessary for the body, prayer and meditation are necessary for the soul.",
  "A true unity of heart is the real remedy for the diseases of separatism, hatred, hostility and a great deal of misunderstanding among individuals.",
  "To become one with the infinite and to serve God in all creation should be the goal of life.",
  "Discrimination and dispassion are the two wings of the soul, which will take you to the everlasting home of freedom and blessedness.",
  "He who dies to the lower self, rises to the immortal. There is nothing more elevating and sublime than to be a witness to the divine presence in all beings, and to strive to awaken that consciousness into others, too.",
  "The root evil which has brought about your bondage is Moha.",
  "The objects of the world act as intoxicants. Money is opium. Man to woman, and woman to man is wine. Position is Ganjah. Power is brandy. Landed property is champagne.",
  "Mind is a bundle of the memories of yesterday and day before yesterday.",
  "Never sit idle, craving God to help you; but be up and doing.",
  "The thinker, the experiencer, is not separate from what is experienced.",
  "Find out the speaker of speech, the seer of sights, the hearer of sounds. You will attain immortality.",
  "There is no greater error than spiritual pride. Moral and spiritual pride is more dangerous than the ordinary pride of wealth and power.",
  "Renounce the world and realise the Self.",
  "The initial stages in Sadhana will be one of ups and downs.",
  "Instruction in material and practical affairs should keep pace with instruction in Divine things.",
  "Peace, God, Atma, Brahman, Immortal, Emancipation are synonymous terms",
  "The flesh wars ceaselessly against the Spirit. Therefore be ever vigilant.",
  "You will have to lead a pure life. Your preceptor cannot do this for you.",
  "The Lords’s ways are mysterious. There is something good even in all seeming failures. You are not able to see that now. Time will reveal it. Be patient.",
  "Never worry about what other people say or think. Do right. Have a clear conscience and roam about happily.",
  "Your strength should not be the strength of gun and bank-balance. It should be the invincible strength born of wisdom and discrimination.",
  "Do not hate the evil-hearted, the jealous and the selfish. It is they who promote your salvation.",
  "The evil man throws dust in the eyes of his discrimination and discernment.",
  "Obstacles and unfavourable circumstances are God-sent chances to make you more steady and strong in will.",
  "Be good. Do good. Serve, love, give, purify, meditate, realise. This is the religion of Siva. This is the religion of the members of the Divine Life Society.",
  "It is divinity that shapes, not only your ends, but also your acts, your words and thoughts.",
  "There is no duality in reality. All modifications are illusory.",
  "Be righteous and simple in principle. Then your action will automatically be moral.",
  "Do not be hasty. Restrain your emotions. Think quietly. Have a serene mind. Act prudently, cautiously, intelligently.",
  "Work is worship. Dedicate it to God.",
  "Selflessness needs no extraneous expression.",
  "One of the greatest needs of life is meditation on spiritual values.",
  "Enter the silence. Pray to the Lord. Listen to the Lord.",
  "Commence your journey on the divine path from today. All your anxiety and worry will end then and there.",
  "Science is not the enemy of religion but a preparation for it",
  "Solve first the ‘who am I?’ problem. All other problems will be automatically solved.",
  "That something which is beyond the scientist’s invention is God.",
  "Spiritual Sadhana is an uphill work. You must have tremendous patience and perseverance.",
  "Life is not fully lived, life has not been fully realised, if you do not serve and love entire humanity.",
  "Nothing will die. All things will change. This is the fundamental truth.",
  "Production or destruction are only phenomena. In reality, there is nothing produced or destroyed.",
  "Deep, deep is that supreme Silence. Peace of the Soul is Infinite, Immeasurable.",
  "The nearer one approaches the Truth, the happier one becomes. For the essential nature of Truth is positive, Absolute Bliss.",
  "No real philosophy can be visualised without self-analysis.",
  "Do not bother about spiritual experiences. Go ahead with your Sadhana. Knowledge dawns of its own accord.",
  "Book learning or erudition is only chaf. Knowledge of Atma alone is the kernel or essence.",
  "Follow the right unswervingly, at any cost. Care not for public opinion or criticism.",
  "The seer is the unchanging, non-dual Atma or Soul. The seen is the changing, visible universe and the mind.",
  "Release or freedom lies in the loss of the little self or self-arrogating personality.",
  "Without developing intuition, the intellectual man remains imperfect.",
  "The first step in the spiritual path is the selfless service of humanity.",
  "Wish good to all beings. This will enrich your life and make you happy and peaceful.",
  "The secret of beauty is not dress and ornaments, but good character and the possession of divine virtues.",
  "Selfless service is the watchword along the road to salvation.",
  "An hour’s service of the sick, with divine Bhav is better than a year’s pilgrimage to Thirtas.",
  "The secret of true life is in the love of God and the service of humanity.",
  "Make discrimination-cum-non-attachment your sword to cut the tree of samsara.",
  "Each time you yield to the dictates of sensual pleasure, you weaken your power of resistance.",
  "Control the tongue. You will control all desires.",
  "There are pitfalls in every step in Yoga. Therefore have a Guru or guide to lead you on.",
  "Smoking is a greater curse than drinking. Give up smoking at once, from today.",
  "God walks in the garb of a beggar. He moans in pain in the guise of the sick. Open your eyes. See him in all. Serve all. Love all.",
  "Where is peace? It is in the heart of a desireless man, who has controlled his senses and the mind.",
  "Peace and bliss are not to be found in books, churches or monasteries. It is realised when knowledge of Atma dawns.",
  "You have wasted much of your life. A little time is left. Make the best use of it. You too can realize God and be ever happy.",
  "The real life consists of discipline, devotion, study of sacred scriptures and meditation on God.",
  "Sadhana is catching hold of one ideal and sticking to it at all costs, even at the risk of life.",
  "Life on earth is a school for wisdom and realisation of the Self or Atman.",
  "Passion makes on begar of beggars and blind.",
  "Life and society cannot exist without struggle or fighting.",
  "Renunciation is not mere asceticism. It is annihilation of selfishness, egoism and cravings.",
  "Never behold life physically. Study it psychically. Realise it spiritually.",
  "A real hero rejoices in suffering.",
  "A vacant mind is ever-distressed. It is the devil’s workshop. Be thoughtful.",
  "Every failure is a stepping stone to success. Nil desperandum. March forward, O hero!",
  "Continue japa and meditation. You will feel joy and taste bliss inexpressible after some time.",
  "Acquire spiritual strength by resistance to the opposites.",
  "Self-realisation must become a passion with you.",
  "Sensual pleasures, like Ghee when pored on fire, intensify all the more, when enjoyed.",
  "You need not wait for ethical perfection, before you start meditation.",
  "Ignorance is a kind of potent anaesthetic. Original ignorance is the same thing as original sin.",
  "Drive this body car intelligently. Relax perfectly. Breathe rhythmically. Meditation regularly. You will enjoy happiness, health and long life.",
  "Life glides on the joyous wings of hope.",
  "Let good thoughts be the rosary of every mind.",
  "O Ram! That which quickens self-realisation, that which bestows awareness, is initiation.",
  "If you can drink nitric acid, you have done no better than a straw. If you can chew iron nails and glass pieces, you have done nothing. This has nothing to do with Yoga. Conquer the mind. You have done everything.",
  "An act is good if prompted by good motive and good will.",
  "Care not for criticism when you are on the right path. Yield not to flattery.",
  "Tolerance is a sign of advancement in the spiritual life.",
  "Every day people are dying around us and yet men think they will never die. This is Maya.",
  "The chief beauty of life is sacrifice of one’s dearest interest at the altar of Truth.",
  "The end of life is spiritual illumination.",
  "There is an Unchanging and Permanent thing behind the ever-changing and ephemeral phenomena.",
  "Your duty is to realise God. This includes all other duties.",
  "Blame and praise are sheer vibrations in the air. Soar above them.",
  "Every disease is Karmic purgation.",
  "Be thou as compassionate as Buddha, as pure as Bhishma, as truthful as Harischandra, as brave as Bhima.",
  "Feel that you are serving the Lord and the Lord alone in the members of your family.",
  "Life is rich if you are simple and humble.",
  "All works are equal service of humanity as a whole and have the same merit. There is no such thinking as menial service.",
  "Mind is at once the venue of man’s bondage and release.",
  "In the beginning, Japa and meditation are very dry and unpalatable and distasteful.",
  "More than food, water and fire, man’s need is sympathy, kindness and brotherhood.",
  "Vain pundits with pedantry get the whey only, churning the Shastras, but devotees get the butter.",
  "Regain your lost divinity. There is no time to lose. Death marches close to your heels.",
  "Uncongenial atmosphere, unfavourable environments and obstacles will help one only in carrying on the struggle more vigorously.",
  "Remember God at all times. If you cannot do this, remember death at all times. Either of the two will lead you to emancipation and freedom.",
  "A saint prevents many ship-wrecks in the lives of many human beings.",
  "He who practises renunciation and meditation, serves the world more than the social and political leaders, platform lectures, and founders of institutions.",
  "You can give up wife and children, you can abandon wealth, but it is difficult to relinquish fame.",
  "You live, because you share the universal life.",
  "That which is beyond caste, creed, family and lineage, that which is free form differentiation is Brahman or the Infinite.",
  "Truth absolute can be that which is one without a second, non-dual and homogeneous.",
  "There is nothing that cannot be attained in the fourteen worlds by that man who is a perfect celibate.",
  "The King of England renounced an Empire for the sake of a woman. How much greater renunciation you should have, if you wish to attain God-realisation.",
  "Pocket insults when offered. Distribute a few pies to the lame, blind and to the hungry months as you walk along the streets.",
  "To feel “I am non-doer and non-enjoyer”, is Gyana.",
  "Materialistic life leads you to fear, anxiety, birth, decay and death as there is no essence of the Immortal Soul in it.",
  "Discrimination between the “seer” and the “seen” is the road leading to the realisation of the Truth.",
  "Man complicates his life by increasing his desires for more and more objects.",
  "Even a little meditation daily will raise you a little higher and a little nearer to God.",
  "Luxury is a curse. It will weaken you.",
  "If you want God, you must turn your back to worldly enjoyments.",
  "You are creating a hell through your own thoughts. Think of the good.",
  "The most devitalising and demoralising of pleasures is the sex-pleasure.",
];
